from searx.tests.engines.test_bing import *  # noqa
from searx.tests.engines.test_bing_images import *  # noqa
from searx.tests.engines.test_bing_news import *  # noqa
from searx.tests.engines.test_blekko_images import *  # noqa
from searx.tests.engines.test_btdigg import *  # noqa
from searx.tests.engines.test_currency_convert import *  # noqa
from searx.tests.engines.test_dailymotion import *  # noqa
from searx.tests.engines.test_deezer import *  # noqa
from searx.tests.engines.test_deviantart import *  # noqa
from searx.tests.engines.test_digg import *  # noqa
from searx.tests.engines.test_duckduckgo import *  # noqa
from searx.tests.engines.test_duckduckgo_definitions import *  # noqa
from searx.tests.engines.test_dummy import *  # noqa
from searx.tests.engines.test_faroo import *  # noqa
from searx.tests.engines.test_flickr import *  # noqa
from searx.tests.engines.test_flickr_noapi import *  # noqa
from searx.tests.engines.test_gigablast import *  # noqa
from searx.tests.engines.test_github import *  # noqa
from searx.tests.engines.test_google import *  # noqa
from searx.tests.engines.test_google_images import *  # noqa
from searx.tests.engines.test_google_news import *  # noqa
from searx.tests.engines.test_kickass import *  # noqa
from searx.tests.engines.test_mediawiki import *  # noqa
from searx.tests.engines.test_mixcloud import *  # noqa
from searx.tests.engines.test_openstreetmap import *  # noqa
from searx.tests.engines.test_photon import *  # noqa
from searx.tests.engines.test_piratebay import *  # noqa
from searx.tests.engines.test_qwant import *  # noqa
from searx.tests.engines.test_searchcode_code import *  # noqa
from searx.tests.engines.test_searchcode_doc import *  # noqa
from searx.tests.engines.test_soundcloud import *  # noqa
from searx.tests.engines.test_spotify import *  # noqa
from searx.tests.engines.test_stackoverflow import *  # noqa
from searx.tests.engines.test_startpage import *  # noqa
from searx.tests.engines.test_subtitleseeker import *  # noqa
from searx.tests.engines.test_swisscows import *  # noqa
from searx.tests.engines.test_twitter import *  # noqa
from searx.tests.engines.test_vimeo import *  # noqa
from searx.tests.engines.test_www1x import *  # noqa
from searx.tests.engines.test_www500px import *  # noqa
from searx.tests.engines.test_yacy import *  # noqa
from searx.tests.engines.test_yahoo import *  # noqa
from searx.tests.engines.test_youtube_api import *  # noqa
from searx.tests.engines.test_youtube_noapi import *  # noqa
from searx.tests.engines.test_yahoo_news import *  # noqa
