from searx.tests.engines.test_bing import *  # noqa
from searx.tests.engines.test_deezer import *  # noqa
from searx.tests.engines.test_dummy import *  # noqa
from searx.tests.engines.test_flickr import *  # noqa
from searx.tests.engines.test_github import *  # noqa
from searx.tests.engines.test_mixcloud import *  # noqa
from searx.tests.engines.test_searchcode_code import *  # noqa
from searx.tests.engines.test_searchcode_doc import *  # noqa
from searx.tests.engines.test_youtube import *  # noqa
