from searx.tests.engines.test_bing import *  # noqa
from searx.tests.engines.test_bing_images import *  # noqa
from searx.tests.engines.test_bing_news import *  # noqa
from searx.tests.engines.test_btdigg import *  # noqa
from searx.tests.engines.test_dailymotion import *  # noqa
from searx.tests.engines.test_deezer import *  # noqa
from searx.tests.engines.test_deviantart import *  # noqa
from searx.tests.engines.test_digg import *  # noqa
from searx.tests.engines.test_dummy import *  # noqa
from searx.tests.engines.test_flickr import *  # noqa
from searx.tests.engines.test_flickr_noapi import *  # noqa
from searx.tests.engines.test_github import *  # noqa
from searx.tests.engines.test_www1x import *  # noqa
from searx.tests.engines.test_google_images import *  # noqa
from searx.tests.engines.test_google_news import *  # noqa
from searx.tests.engines.test_kickass import *  # noqa
from searx.tests.engines.test_mixcloud import *  # noqa
from searx.tests.engines.test_piratebay import *  # noqa
from searx.tests.engines.test_searchcode_code import *  # noqa
from searx.tests.engines.test_searchcode_doc import *  # noqa
from searx.tests.engines.test_soundcloud import *  # noqa
from searx.tests.engines.test_stackoverflow import *  # noqa
from searx.tests.engines.test_vimeo import *  # noqa
from searx.tests.engines.test_www500px import *  # noqa
from searx.tests.engines.test_youtube import *  # noqa
