# -*- coding: utf-8 -*-
# list of language codes
# this file is generated automatically by utils/update_search_languages.py

language_codes = (
    (u"ach", u"Acoli", u"", u""),
    (u"af", u"Afrikaans", u"", u"Afrikaans"),
    (u"ak", u"Akan", u"", u""),
    (u"als", u"Alemannisch", u"", u"Alemannic"),
    (u"am", u"አማርኛ", u"", u"Amharic"),
    (u"an", u"Aragonés", u"", u"Aragonese"),
    (u"ar-SA", u"العربية", u"المملكة العربية السعودية", u"Arabic"),
    (u"arz", u"مصرى (Maṣri)", u"", u"Egyptian Arabic"),
    (u"ast", u"Asturianu", u"", u"Asturian"),
    (u"az", u"Azərbaycanca", u"", u"Azerbaijani"),
    (u"azb", u"تۆرکجه", u"", u"South Azerbaijani"),
    (u"ba", u"Башҡорт", u"", u"Bashkir"),
    (u"ban", u"Balinese", u"", u""),
    (u"bar", u"Boarisch", u"", u"Bavarian"),
    (u"be", u"Беларуская", u"", u"Belarusian"),
    (u"bem", u"Ichibemba", u"", u""),
    (u"bg-BG", u"Български", u"България", u"Bulgarian"),
    (u"bn", u"বাংলা", u"", u"Bengali"),
    (u"bpy", u"ইমার ঠার/বিষ্ণুপ্রিয়া মণিপুরী", u"", u"Bishnupriya Manipuri"),
    (u"br", u"Brezhoneg", u"", u"Breton"),
    (u"bs", u"Bosanski", u"", u"Bosnian"),
    (u"bug", u"Basa Ugi", u"", u"Buginese"),
    (u"ca", u"Català", u"", u"Catalan"),
    (u"ca-CT", u"Català", u"", u"Catalan"),
    (u"ca-ES", u"Català", u"Espanya", u"Catalan"),
    (u"ce", u"Нохчийн", u"", u"Chechen"),
    (u"ceb", u"Sinugboanong Binisaya", u"", u"Cebuano"),
    (u"chr", u"ᏣᎳᎩ", u"", u""),
    (u"ckb", u"Soranî / کوردی", u"", u"Sorani"),
    (u"co", u"Corsican", u"", u""),
    (u"crs", u"Seychellois Creole", u"", u""),
    (u"cs-CZ", u"Čeština", u"Česko", u"Czech"),
    (u"cv", u"Чăваш", u"", u"Chuvash"),
    (u"cy", u"Cymraeg", u"", u"Welsh"),
    (u"da-DK", u"Dansk", u"Danmark", u"Danish"),
    (u"de", u"Deutsch", u"", u"German"),
    (u"de-AT", u"Deutsch", u"Österreich", u"German"),
    (u"de-CH", u"Deutsch", u"Schweiz", u"German"),
    (u"de-DE", u"Deutsch", u"Deutschland", u"German"),
    (u"ee", u"Eʋegbe", u"", u""),
    (u"el-GR", u"Ελληνικά", u"Ελλάδα", u"Greek"),
    (u"en", u"English", u"", u"English"),
    (u"en-AU", u"English", u"Australia", u"English"),
    (u"en-CA", u"English", u"Canada", u"English"),
    (u"en-GB", u"English", u"United Kingdom", u"English"),
    (u"en-ID", u"English", u"Indonesia", u"English"),
    (u"en-IE", u"English", u"Ireland", u"English"),
    (u"en-IN", u"English", u"India", u"English"),
    (u"en-MY", u"English", u"Malaysia", u"English"),
    (u"en-NZ", u"English", u"New Zealand", u"English"),
    (u"en-PH", u"English", u"Philippines", u"English"),
    (u"en-SG", u"English", u"Singapore", u"English"),
    (u"en-US", u"English", u"United States", u"English"),
    (u"en-ZA", u"English", u"South Africa", u"English"),
    (u"eo", u"Esperanto", u"", u"Esperanto"),
    (u"es", u"Español", u"", u"Spanish"),
    (u"es-AR", u"Español", u"Argentina", u"Spanish"),
    (u"es-CL", u"Español", u"Chile", u"Spanish"),
    (u"es-CO", u"Español", u"Colombia", u"Spanish"),
    (u"es-ES", u"Español", u"España", u"Spanish"),
    (u"es-MX", u"Español", u"México", u"Spanish"),
    (u"es-PE", u"Español", u"Perú", u"Spanish"),
    (u"es-US", u"Español", u"Estados Unidos", u"Spanish"),
    (u"et-EE", u"Eesti", u"Eesti", u"Estonian"),
    (u"eu", u"Euskara", u"", u"Basque"),
    (u"fa", u"فارسی", u"", u"Persian"),
    (u"fi-FI", u"Suomi", u"Suomi", u"Finnish"),
    (u"fo", u"Føroyskt", u"", u"Faroese"),
    (u"fr", u"Français", u"", u"French"),
    (u"fr-BE", u"Français", u"Belgique", u"French"),
    (u"fr-CA", u"Français", u"Canada", u"French"),
    (u"fr-CH", u"Français", u"Suisse", u"French"),
    (u"fr-FR", u"Français", u"France", u"French"),
    (u"fy", u"Frysk", u"", u"West Frisian"),
    (u"ga", u"Gaeilge", u"", u"Irish"),
    (u"gaa", u"Ga", u"", u""),
    (u"gd", u"Gàidhlig", u"", u"Scottish Gaelic"),
    (u"gl", u"Galego", u"", u"Galician"),
    (u"gn", u"Guarani", u"", u""),
    (u"gu", u"ગુજરાતી", u"", u"Gujarati"),
    (u"ha", u"Hausa", u"", u""),
    (u"haw", u"ʻŌlelo HawaiʻI", u"", u""),
    (u"he-IL", u"עברית", u"ישראל", u"Hebrew"),
    (u"hi", u"हिन्दी", u"", u"Hindi"),
    (u"hr-HR", u"Hrvatski", u"Hrvatska", u"Croatian"),
    (u"hsb", u"Hornjoserbsce", u"", u"Upper Sorbian"),
    (u"ht", u"Krèyol ayisyen", u"", u"Haitian"),
    (u"hu-HU", u"Magyar", u"Magyarország", u"Hungarian"),
    (u"hy", u"Հայերեն", u"", u"Armenian"),
    (u"ia", u"Interlingua", u"", u"Interlingua"),
    (u"id-ID", u"Bahasa Indonesia", u"Indonesia", u"Indonesian"),
    (u"ig", u"Igbo", u"", u""),
    (u"io", u"Ido", u"", u"Ido"),
    (u"is", u"Íslenska", u"", u"Icelandic"),
    (u"it", u"Italiano", u"", u"Italian"),
    (u"it-CH", u"Italiano", u"Svizzera", u"Italian"),
    (u"it-IT", u"Italiano", u"Italia", u"Italian"),
    (u"iw", u"עברית", u"", u""),
    (u"ja-JP", u"日本語", u"日本", u"Japanese"),
    (u"jv", u"Basa Jawa", u"", u"Javanese"),
    (u"ka", u"ქართული", u"", u"Georgian"),
    (u"kg", u"Kongo", u"", u""),
    (u"kk", u"Қазақша", u"", u"Kazakh"),
    (u"km", u"ខ្មែរ", u"", u""),
    (u"kn", u"ಕನ್ನಡ", u"", u"Kannada"),
    (u"ko-KR", u"한국어", u"대한민국", u"Korean"),
    (u"kri", u"Krio (Sierra Leone)", u"", u""),
    (u"ku", u"Kurdî / كوردی", u"", u"Kurdish"),
    (u"ky", u"Кыргызча", u"", u"Kirghiz"),
    (u"la", u"Latina", u"", u"Latin"),
    (u"lb", u"Lëtzebuergesch", u"", u"Luxembourgish"),
    (u"lg", u"Luganda", u"", u""),
    (u"li", u"Limburgs", u"", u"Limburgish"),
    (u"lmo", u"Lumbaart", u"", u"Lombard"),
    (u"ln", u"Lingála", u"", u""),
    (u"lo", u"ລາວ", u"", u""),
    (u"loz", u"Lozi", u"", u""),
    (u"lt-LT", u"Lietuvių", u"Lietuva", u"Lithuanian"),
    (u"lua", u"Luba-Lulua", u"", u""),
    (u"lv-LV", u"Latviešu", u"Latvijas Republika", u"Latvian"),
    (u"mfe", u"Kreol Morisien", u"", u""),
    (u"mg", u"Malagasy", u"", u"Malagasy"),
    (u"mi", u"Maori", u"", u""),
    (u"min", u"Minangkabau", u"", u"Minangkabau"),
    (u"mk", u"Македонски", u"", u"Macedonian"),
    (u"ml", u"മലയാളം", u"", u"Malayalam"),
    (u"mn", u"Монгол", u"", u"Mongolian"),
    (u"mr", u"मराठी", u"", u"Marathi"),
    (u"mrj", u"Кырык Мары (Kyryk Mary)", u"", u"Hill Mari"),
    (u"ms-MY", u"Bahasa Melayu", u"Malaysia", u"Malay"),
    (u"mt", u"Malti", u"", u""),
    (u"my", u"မြန်မာဘာသာ", u"", u"Burmese"),
    (u"mzn", u"مَزِروني", u"", u"Mazandarani"),
    (u"nah", u"Nāhuatl", u"", u"Nahuatl"),
    (u"nap", u"Nnapulitano", u"", u"Neapolitan"),
    (u"nds-nl", u"Plattdüütsch", u"Nedderlannen", u"Low Saxon"),
    (u"ne", u"नेपाली", u"", u"Nepali"),
    (u"new", u"नेपाल भाषा", u"", u"Newar"),
    (u"nl", u"Nederlands", u"", u"Dutch"),
    (u"nl-BE", u"Nederlands", u"België", u"Dutch"),
    (u"nl-NL", u"Nederlands", u"Nederland", u"Dutch"),
    (u"nn", u"Nynorsk", u"", u"Norwegian (Nynorsk)"),
    (u"no-NO", u"Norsk (Bokmål)", u"Norge", u"Norwegian (Bokmål)"),
    (u"nso", u"Northern Sotho", u"", u""),
    (u"ny", u"Nyanja", u"", u""),
    (u"nyn", u"Runyankore", u"", u""),
    (u"oc", u"Occitan", u"", u"Occitan"),
    (u"om", u"Oromoo", u"", u""),
    (u"or", u"ଓଡ଼ିଆ", u"", u"Oriya"),
    (u"os", u"Иронау", u"", u"Ossetian"),
    (u"pa", u"ਪੰਜਾਬੀ", u"", u"Punjabi"),
    (u"pcm", u"Nigerian Pidgin", u"", u""),
    (u"pl-PL", u"Polski", u"Rzeczpospolita Polska", u"Polish"),
    (u"pms", u"Piemontèis", u"", u"Piedmontese"),
    (u"pnb", u"شاہ مکھی پنجابی (Shāhmukhī Pañjābī)", u"", u"Western Punjabi"),
    (u"ps", u"پښتو", u"", u""),
    (u"pt", u"Português", u"", u"Portuguese"),
    (u"pt-BR", u"Português", u"Brasil", u"Portuguese"),
    (u"pt-PT", u"Português", u"Portugal", u"Portuguese"),
    (u"qu", u"Runa Simi", u"", u"Quechua"),
    (u"rm", u"Rumantsch", u"", u""),
    (u"rn", u"Ikirundi", u"", u""),
    (u"ro-RO", u"Română", u"România", u"Romanian"),
    (u"ru-RU", u"Русский", u"Россия", u"Russian"),
    (u"rw", u"Kinyarwanda", u"", u""),
    (u"sa", u"संस्कृतम्", u"", u"Sanskrit"),
    (u"sah", u"Саха тыла (Saxa Tyla)", u"", u"Sakha"),
    (u"scn", u"Sicilianu", u"", u"Sicilian"),
    (u"sco", u"Scots", u"", u"Scots"),
    (u"sd", u"Sindhi", u"", u""),
    (u"sh", u"Srpskohrvatski / Српскохрватски", u"", u"Serbo-Croatian"),
    (u"si", u"සිංහල", u"", u"Sinhalese"),
    (u"sk-SK", u"Slovenčina", u"Slovenská republika", u"Slovak"),
    (u"sl", u"Slovenščina", u"", u"Slovenian"),
    (u"sl-SI", u"Slovenščina", u"Slovenija", u"Slovenian"),
    (u"sl-SL", u"Slovenščina", u"Sierra Leone", u"Slovenian"),
    (u"sn", u"Chishona", u"", u""),
    (u"so", u"Soomaali", u"", u""),
    (u"sq", u"Shqip", u"", u"Albanian"),
    (u"sr-ME", u"Српски / Srpski", u"Црна Гора", u"Serbian"),
    (u"st", u"Southern Sotho", u"", u""),
    (u"su", u"Basa Sunda", u"", u"Sundanese"),
    (u"sv-SE", u"Svenska", u"Sverige", u"Swedish"),
    (u"sw", u"Kiswahili", u"", u"Swahili"),
    (u"ta", u"தமிழ்", u"", u"Tamil"),
    (u"te", u"తెలుగు", u"", u"Telugu"),
    (u"tg", u"Тоҷикӣ", u"", u"Tajik"),
    (u"th-TH", u"ไทย", u"ไทย", u"Thai"),
    (u"ti", u"ትግርኛ", u"", u""),
    (u"tk", u"Turkmen", u"", u""),
    (u"tl-PH", u"Tagalog", u"Pilipinas", u"Tagalog"),
    (u"tlh", u"Klingon", u"", u""),
    (u"tn", u"Tswana", u"", u""),
    (u"to", u"Lea Fakatonga", u"", u""),
    (u"tr-TR", u"Türkçe", u"Türkiye", u"Turkish"),
    (u"tt", u"Tatarça / Татарча", u"", u"Tatar"),
    (u"tum", u"Tumbuka", u"", u""),
    (u"tw", u"Twi", u"", u""),
    (u"ug", u"ئۇيغۇرچە", u"", u""),
    (u"uk-UA", u"Українська", u"Україна", u"Ukrainian"),
    (u"ur", u"اردو", u"", u"Urdu"),
    (u"uz", u"O‘zbek", u"", u"Uzbek"),
    (u"vec", u"Vèneto", u"", u"Venetian"),
    (u"vi-VN", u"Tiếng Việt", u"Công Hòa Xã Hội Chủ Nghĩa Việt Nam", u"Vietnamese"),
    (u"vo", u"Volapük", u"", u"Volapük"),
    (u"wa", u"Walon", u"", u"Walloon"),
    (u"war", u"Winaray", u"", u"Waray-Waray"),
    (u"wo", u"Wolof", u"", u""),
    (u"xh", u"Xhosa", u"", u""),
    (u"yi", u"ייִדיש", u"", u"Yiddish"),
    (u"yo", u"Yorùbá", u"", u"Yoruba"),
    (u"zh", u"中文", u"", u"Chinese"),
    (u"zh-CN", u"中文", u"中国", u"Chinese"),
    (u"zh-HK", u"中文", u"香港", u"Chinese"),
    (u"zh-TW", u"中文", u"台湾", u"Chinese"),
    (u"zu", u"Isizulu", u"", u"")
)
