# -*- coding: utf-8 -*-
# list of language codes
# this file is generated automatically by utils/fetch_languages.py
language_codes = \
(   ('af-ZA', 'Afrikaans', '', 'Afrikaans'),
    ('am-ET', 'አማርኛ', '', 'Amharic'),
    ('ar-EG', 'العربية', '', 'Arabic'),
    ('az-AZ', 'Azərbaycan', '', 'Azerbaijani'),
    ('be-BY', 'Беларуская', '', 'Belarusian'),
    ('bg-BG', 'Български', '', 'Bulgarian'),
    ('bn-BD', 'বাংলা', '', 'Bangla'),
    ('bs-BA', 'Bosanski', '', 'Bosnian'),
    ('ca-ES', 'Català', '', 'Catalan'),
    ('cs-CZ', 'Čeština', '', 'Czech'),
    ('da-DK', 'Dansk', '', 'Danish'),
    ('de', 'Deutsch', '', 'German'),
    ('de-AT', 'Deutsch', 'Österreich', 'German'),
    ('de-CH', 'Deutsch', 'Schweiz', 'German'),
    ('de-DE', 'Deutsch', 'Deutschland', 'German'),
    ('el-GR', 'Ελληνικά', '', 'Greek'),
    ('en', 'English', '', 'English'),
    ('en-AU', 'English', 'Australia', 'English'),
    ('en-CA', 'English', 'Canada', 'English'),
    ('en-GB', 'English', 'United Kingdom', 'English'),
    ('en-IE', 'English', 'Ireland', 'English'),
    ('en-IN', 'English', 'India', 'English'),
    ('en-NZ', 'English', 'New Zealand', 'English'),
    ('en-PH', 'English', 'Philippines', 'English'),
    ('en-SG', 'English', 'Singapore', 'English'),
    ('en-US', 'English', 'United States', 'English'),
    ('es', 'Español', '', 'Spanish'),
    ('es-AR', 'Español', 'Argentina', 'Spanish'),
    ('es-CL', 'Español', 'Chile', 'Spanish'),
    ('es-ES', 'Español', 'España', 'Spanish'),
    ('es-MX', 'Español', 'México', 'Spanish'),
    ('et-EE', 'Eesti', '', 'Estonian'),
    ('fa-IR', 'فارسی', '', 'Persian'),
    ('fi-FI', 'Suomi', '', 'Finnish'),
    ('fo-FO', 'Føroyskt', '', 'Faroese'),
    ('fr', 'Français', '', 'French'),
    ('fr-BE', 'Français', 'Belgique', 'French'),
    ('fr-CA', 'Français', 'Canada', 'French'),
    ('fr-CH', 'Français', 'Suisse', 'French'),
    ('fr-FR', 'Français', 'France', 'French'),
    ('he-IL', 'עברית', '', 'Hebrew'),
    ('hr-HR', 'Hrvatski', '', 'Croatian'),
    ('hu-HU', 'Magyar', '', 'Hungarian'),
    ('hy-AM', 'Հայերեն', '', 'Armenian'),
    ('id-ID', 'Indonesia', '', 'Indonesian'),
    ('is-IS', 'Íslenska', '', 'Icelandic'),
    ('it-IT', 'Italiano', '', 'Italian'),
    ('ja-JP', '日本語', '', 'Japanese'),
    ('ka-GE', 'ქართული', '', 'Georgian'),
    ('kk-KZ', 'Қазақ Тілі', '', 'Kazakh'),
    ('km-KH', 'ខ្មែរ', '', 'Khmer'),
    ('ko-KR', '한국어', '', 'Korean'),
    ('ky-KG', 'Кыргызча', '', 'Kyrgyz'),
    ('lo-LA', 'ລາວ', '', 'Lao'),
    ('lt-LT', 'Lietuvių', '', 'Lithuanian'),
    ('lv-LV', 'Latviešu', '', 'Latvian'),
    ('mk-MK', 'Македонски', '', 'Macedonian'),
    ('mn-MN', 'Монгол', '', 'Mongolian'),
    ('ms-MY', 'Melayu', '', 'Malay'),
    ('mt-MT', 'Malti', '', 'Maltese'),
    ('nb-NO', 'Norsk Bokmål', '', 'Norwegian Bokmål'),
    ('ne-NP', 'नेपाली', '', 'Nepali'),
    ('nl', 'Nederlands', '', 'Dutch'),
    ('nl-BE', 'Nederlands', 'België', 'Dutch'),
    ('nl-NL', 'Nederlands', 'Nederland', 'Dutch'),
    ('pl-PL', 'Polski', '', 'Polish'),
    ('pt', 'Português', '', 'Portuguese'),
    ('pt-BR', 'Português', 'Brasil', 'Portuguese'),
    ('pt-PT', 'Português', 'Portugal', 'Portuguese'),
    ('ro-RO', 'Română', '', 'Romanian'),
    ('ru-RU', 'Русский', '', 'Russian'),
    ('rw-RW', 'Kinyarwanda', '', 'Kinyarwanda'),
    ('si-LK', 'සිංහල', '', 'Sinhala'),
    ('sk-SK', 'Slovenčina', '', 'Slovak'),
    ('sl-SI', 'Slovenščina', '', 'Slovenian'),
    ('so-SO', 'Soomaali', '', 'Somali'),
    ('sq-AL', 'Shqip', '', 'Albanian'),
    ('sr-RS', 'Srpski', '', 'Serbian'),
    ('sv-SE', 'Svenska', '', 'Swedish'),
    ('sw-TZ', 'Kiswahili', '', 'Swahili'),
    ('tg-TJ', 'Тоҷикӣ', '', 'Tajik'),
    ('th-TH', 'ไทย', '', 'Thai'),
    ('ti-ET', 'ትግርኛ', '', 'Tigrinya'),
    ('tk-TM', 'Türkmen Dili', '', 'Turkmen'),
    ('tr-TR', 'Türkçe', '', 'Turkish'),
    ('uk-UA', 'Українська', '', 'Ukrainian'),
    ('ur-PK', 'اردو', '', 'Urdu'),
    ('uz-UZ', 'O‘Zbek', '', 'Uzbek'),
    ('vi-VN', 'Tiếng Việt', '', 'Vietnamese'),
    ('zh', '中文', '', 'Chinese'),
    ('zh-CN', '中文', '中国', 'Chinese'),
    ('zh-TW', '中文', '台灣', 'Chinese'))