language_codes = (
    ("ar_XA", "Arabic", "Arabia"),
    ("bg_BG", "Bulgarian", "Bulgaria"),
    ("cs_CZ", "Czech", "Czech Republic"),
    ("de_DE", "German", "Germany"),
    ("da_DK", "Danish", "Denmark"),
    ("de_AT", "German", "Austria"),
    ("de_CH", "German", "Switzerland"),
    ("el_GR", "Greek", "Greece"),
    ("en_AU", "English", "Australia"),
    ("en_CA", "English", "Canada"),
    ("en_GB", "English", "United Kingdom"),
    ("en_ID", "English", "Indonesia"),
    ("en_IE", "English", "Ireland"),
    ("en_IN", "English", "India"),
    ("en_MY", "English", "Malaysia"),
    ("en_NZ", "English", "New Zealand"),
    ("en_PH", "English", "Philippines"),
    ("en_SG", "English", "Singapore"),
    ("en_US", "English", "United States"),
    ("en_XA", "English", "Arabia"),
    ("en_ZA", "English", "South Africa"),
    ("es_AR", "Spanish", "Argentina"),
    ("es_CL", "Spanish", "Chile"),
    ("es_ES", "Spanish", "Spain"),
    ("es_MX", "Spanish", "Mexico"),
    ("es_US", "Spanish", "United States"),
    ("es_XL", "Spanish", "Latin America"),
    ("et_EE", "Estonian", "Estonia"),
    ("fi_FI", "Finnish", "Finland"),
    ("fr_BE", "French", "Belgium"),
    ("fr_CA", "French", "Canada"),
    ("fr_CH", "French", "Switzerland"),
    ("fr_FR", "French", "France"),
    ("he_IL", "Hebrew", "Israel"),
    ("hr_HR", "Croatian", "Croatia"),
    ("hu_HU", "Hungarian", "Hungary"),
    ("it_IT", "Italian", "Italy"),
    ("ja_JP", "Japanese", "Japan"),
    ("ko_KR", "Korean", "Korea"),
    ("lt_LT", "Lithuanian", "Lithuania"),
    ("lv_LV", "Latvian", "Latvia"),
    ("nb_NO", "Norwegian", "Norway"),
    ("nl_BE", "Dutch", "Belgium"),
    ("nl_NL", "Dutch", "Netherlands"),
    ("pl_PL", "Polish", "Poland"),
    ("pt_BR", "Portuguese", "Brazil"),
    ("pt_PT", "Portuguese", "Portugal"),
    ("ro_RO", "Romanian", "Romania"),
    ("ru_RU", "Russian", "Russia"),
    ("sk_SK", "Slovak", "Slovak Republic"),
    ("sl_SL", "Slovenian", "Slovenia"),
    ("sv_SE", "Swedish", "Sweden"),
    ("th_TH", "Thai", "Thailand"),
    ("tr_TR", "Turkish", "Turkey"),
    ("uk_UA", "Ukrainian", "Ukraine"),
    ("zh_CN", "Chinese", "China"),
    ("zh_HK", "Chinese", "Hong Kong SAR"),
    ("zh_TW", "Chinese", "Taiwan"))
